spring:
   datasource:
        url: jdbc:h2:mem:testdb;
        driverClassName: org.h2.Driver
        username: sa
        password:
   jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                ddl-auto: update
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
               
server:
    port: 9000
               